# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ self, inputs, ...}: {
    flake.nixosModules.laptopHardware = { config, lib, pkgs, modulesPath, ... }:

    {
	imports = [ (modulesPath + "/installer/scan/not-detected.nix")];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

	fileSystems."/" =
	{ device = "/dev/mapper/luks-7d5088d6-731f-42e8-a51e-1868b2ed0e29";
	    fsType = "ext4";
	};
	
	#fix for hibernation?
	boot.resumeDevice = "/dev/mapper/luks-710f71b8-cdef-4fa2-aca7-0a075b11109a";
	boot.initrd.luks.devices."luks-7d5088d6-731f-42e8-a51e-1868b2ed0e29".device = "/dev/disk/by-uuid/7d5088d6-731f-42e8-a51e-1868b2ed0e29";

	fileSystems."/boot" =
	{ device = "/dev/disk/by-uuid/06E8-D7A6";
	    fsType = "vfat";
	    options = [ "fmask=0077" "dmask=0077" ];
	};

	swapDevices =
	    [ { device = "/dev/mapper/luks-710f71b8-cdef-4fa2-aca7-0a075b11109a"; }
	    ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	hardware.graphics = {
	    enable = true;
	    enable32Bit = true;
	};

	services.xserver.videoDrivers = [ "amdgpu" "nvidia" ];

#	systemd.services.disable-acpi-wake = {
#	    description = "Disable ACPI wake-up triggers for USB and PCIe";
#	    wantedBy = [ "multi-user.target" ];
#	    script = ''
#		# List of devices from your /proc/acpi/wakeup output
#		for dev in XHC0 XHC1 XHC3 XHC4 NHI0 GPP0 GPP6 GP11; do
#		    if grep -q "$dev.*enabled" /proc/acpi/wakeup; then
#			echo $dev > /proc/acpi/wakeup
#		    fi
#		done
#	    '';
#	};

	hardware.nvidia = {
	    prime = {
		offload = {
		    enable = true;
		    enableOffloadCmd = true;
		};
		amdgpuBusId = "PCI:64@0:0:0";
		nvidiaBusId = "PCI:1@0:0:0";

	    };

	    modesetting.enable = true;

	    powerManagement.enable = true;
	    powerManagement.finegrained = true;

	    nvidiaSettings = true;
	    open = true;
	};

    };
}
